### ISSUE TITLE
WTB new command for prepopulation of unreleased changelog section

### ISSUE THREAD

**Issue by rocktavious** [mtdowling/chag#6]
I think this would be a super useful command when initially getting started on writing your unreleased changelog.  It could simple take the git commit messages, maybe even just the commit titles, and generate a list for you from the current commit back towards the last release tag.

Then someone could go and hand edit the changelog, scrap lines that don't need to be there, rewrite others depending on how fancy they want their changlog to be etc 
but it would give you a good jumping off point when starting the unreleased changelog section

Thoughts?

**Comment by mtdowling** [comment]
I think that the best workflow for maintaining a changelog is to modify the changelog as you update your codebase. If a change is significant enough to show up in a changelog, then that change should include adding a new entry to the changelog.

I think that git-commit driven changelogs aren't really written for humans. They're not curated to show the significant changes users need to be aware of when upgrading. By adding a command in chag to generate changelog entries based on git commits, we'd be reinforcing this bad practice with the cost of added complexity.

There are already tools that can generate changelogs from git commits: https://github.com/skywinder/Github-Changelog-Generator/wiki/Alternatives. I'd prefer to keep chag lean and focused on manipulating manually maintained changelogs.
